# Generated by Django 4.0.1 on 2022-01-13 13:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('tractor_num', models.CharField(max_length=255)),
                ('license_num', models.CharField(max_length=255)),
                ('license_state', localflavor.us.models.USStateField(max_length=2)),
                ('license_exp', models.DateField()),
                ('domicile_location', models.CharField(max_length=255)),
                ('social_security_num', localflavor.us.models.USSocialSecurityNumberField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^(?!000|.+0{4})(?:\\d{3}-\\d{2}-\\d{4})$', message='Invalid SSN, make sure the ssn is valid and use the xxx-xx-xxx format')])),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('employee_num', models.CharField(max_length=255, unique=True)),
                ('primary_phone_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email_address', models.EmailField(max_length=255, unique=True)),
                ('home_address', models.CharField(max_length=255)),
                ('mailing_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=50)),
                ('job_num', models.CharField(max_length=25)),
                ('dispatch_date', models.DateField()),
                ('billing_id', models.CharField(max_length=10)),
                ('shipment_id', models.CharField(max_length=25)),
                ('outbound_miles', models.PositiveIntegerField(blank=True, default=0)),
                ('pieces', models.CharField(blank=True, default='0', max_length=10)),
                ('delivery_type', models.CharField(blank=True, max_length=10, null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('layover', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tindall_haul_erect.driver')),
            ],
        ),
    ]
