# Generated by Django 4.0.1 on 2022-02-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
