# Generated by Django 4.0.1 on 2022-02-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversettlement',
            name='load',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='tindall_haul_erect.load'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettlement',
            name='load',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='tindall_haul_erect.load'),
            preserve_default=False,
        ),
    ]
