# Generated by Django 4.0.1 on 2022-01-12 18:49

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_state',
            field=localflavor.us.models.USStateField(max_length=2),
        ),
    ]
