# Generated by Django 4.0.1 on 2022-01-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='billing_id',
            new_name='bill_to',
        ),
    ]
