# Generated by Django 4.0.1 on 2022-02-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0002_billing_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='approval',
            new_name='approved',
        ),
    ]
