# Generated by Django 4.0.1 on 2022-01-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0002_rename_billing_id_load_bill_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='driver',
            new_name='driver_id',
        ),
    ]
