# Generated by Django 4.0.1 on 2022-01-12 21:20

import django.core.validators
from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0003_alter_driver_social_security_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='social_security_num',
            field=localflavor.us.models.USSocialSecurityNumberField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^(?!000|.+0{4})(?:\\d{3}-\\d{2}-\\d{4})$', message='Invalid SSN, make sure the ssn is valid and use the xxx-xx-xxx format')]),
        ),
    ]
