# Generated by Django 4.0.1 on 2022-02-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0003_rename_approval_billing_approved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RateLookup',
            new_name='Rate',
        ),
    ]
