# Generated by Django 4.0.1 on 2022-01-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0003_rename_driver_load_driver_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='driver_id',
            new_name='driver',
        ),
    ]
