# Generated by Django 4.0.1 on 2022-01-12 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0004_alter_driver_social_security_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=50)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tindall_haul_erect.driver')),
            ],
        ),
    ]
