# Generated by Django 4.0.1 on 2022-01-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0004_rename_driver_id_load_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreStressBillingLookup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('outbound_miles', models.PositiveIntegerField()),
                ('base_std_hrs', models.DecimalField(decimal_places=2, max_digits=4)),
                ('base_std_billable_amt', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='UtilitiesBillingLookup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('outbound_miles', models.PositiveIntegerField()),
                ('base_std_hrs', models.DecimalField(decimal_places=2, max_digits=4)),
                ('base_std_billable_amt', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='load',
            name='outbound_miles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
