# Generated by Django 4.0.1 on 2022-01-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0005_prestressbillinglookup_utilitiesbillinglookup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestressbillinglookup',
            name='outbound_miles',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='utilitiesbillinglookup',
            name='outbound_miles',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
