# Generated by Django 4.0.1 on 2022-01-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0006_alter_prestressbillinglookup_outbound_miles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='pieces',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
