# Generated by Django 4.0.1 on 2022-01-13 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0007_alter_load_pieces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_std_hrs', models.DecimalField(decimal_places=2, max_digits=4)),
                ('site_base_std_billable_amt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('addnl_std_hrs', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('sec_stop_hrs', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('wait_start_time', models.TimeField(default=datetime.time(0, 0))),
                ('wait_end_time', models.TimeField(default=datetime.time(0, 0))),
                ('wait_hrs', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('break_hrs', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('fringe_hrs', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('tindall_haul_erect_work_hrs', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tindall_haul_erect.load')),
            ],
        ),
    ]
