# Generated by Django 4.0.1 on 2022-01-13 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0008_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='load',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tindall_haul_erect.load'),
        ),
    ]
