# Generated by Django 4.0.1 on 2022-01-13 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0009_alter_billing_id_alter_billing_load'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='id',
        ),
        migrations.AlterField(
            model_name='billing',
            name='load',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='tindall_haul_erect.load'),
        ),
    ]
