# Generated by Django 4.0.1 on 2022-01-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0010_remove_billing_id_alter_billing_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='delivery_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='load',
            name='shipment_id',
            field=models.CharField(default='', max_length=25),
        ),
    ]
