# Generated by Django 4.0.1 on 2022-01-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0012_ratelookup_unloadingtimelookup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unloadingtimelookup',
            unique_together={('delivery_type', 'pieces')},
        ),
    ]
