# Generated by Django 4.0.1 on 2022-01-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0013_alter_unloadingtimelookup_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSettlement',
            fields=[
                ('billing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='tindall_haul_erect.billing')),
                ('base_std', models.DecimalField(decimal_places=2, max_digits=6)),
                ('addnl_std', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sec_stop', models.DecimalField(decimal_places=2, max_digits=6)),
                ('per_diem', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cancel', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wait', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Break', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fringe', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tindall_haul_erect_work', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettlement',
            fields=[
                ('billing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='tindall_haul_erect.billing')),
                ('base_std', models.DecimalField(decimal_places=2, max_digits=6)),
                ('addnl_std', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sec_stop', models.DecimalField(decimal_places=2, max_digits=6)),
                ('layover', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cancel', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wait', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='billing',
            name='site_base_std_billable_amt',
        ),
    ]
