# Generated by Django 4.0.1 on 2022-01-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0014_driversettlement_sitesettlement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='base_std_hrs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='driversettlement',
            name='Break',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='driversettlement',
            name='addnl_std',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='driversettlement',
            name='base_std',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='driversettlement',
            name='billing',
            field=models.OneToOneField(default=0.0, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='tindall_haul_erect.billing'),
        ),
        migrations.AlterField(
            model_name='driversettlement',
            name='cancel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='driversettlement',
            name='fringe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='driversettlement',
            name='per_diem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='driversettlement',
            name='sec_stop',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='driversettlement',
            name='tindall_haul_erect_work',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='driversettlement',
            name='wait',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sitesettlement',
            name='addnl_std',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sitesettlement',
            name='base_std',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sitesettlement',
            name='cancel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sitesettlement',
            name='layover',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sitesettlement',
            name='sec_stop',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sitesettlement',
            name='wait',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
