# Generated by Django 4.0.1 on 2022-01-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindall_haul_erect', '0015_alter_billing_base_std_hrs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestressbillinglookup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='utilitiesbillinglookup',
            name='id',
        ),
        migrations.AlterField(
            model_name='prestressbillinglookup',
            name='outbound_miles',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='utilitiesbillinglookup',
            name='outbound_miles',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
